-- ============================================================
-- မဟာရန်ကုန် Classic Store
-- Supabase Database Schema
-- Customer + Orders + Products + Stock Management
-- ============================================================

create extension if not exists "pgcrypto";

-- ============================================================
-- 1. PRODUCTS
-- ============================================================

create table if not exists public.products (
    id bigint generated by default as identity primary key,

    name text not null,
    description text,

    price numeric(12,2) not null default 0,

    color text,
    sizes text,

    image_url text,

    stock integer not null default 0,

    active boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint products_price_non_negative
        check (price >= 0),

    constraint products_stock_non_negative
        check (stock >= 0)
);


-- ============================================================
-- 2. CUSTOMERS
-- ============================================================

create table if not exists public.customers (
    id bigint generated by default as identity primary key,

    name text not null,
    phone text not null,

    address text,
    township text,

    note text,

    total_orders integer not null default 0,
    total_spent numeric(12,2) not null default 0,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint customers_total_orders_non_negative
        check (total_orders >= 0),

    constraint customers_total_spent_non_negative
        check (total_spent >= 0)
);


-- ============================================================
-- 3. ORDERS
-- ============================================================

create table if not exists public.orders (
    id bigint generated by default as identity primary key,

    customer_id bigint
        references public.customers(id)
        on delete set null,

    customer_name text not null,
    customer_phone text not null,
    customer_address text,

    total_amount numeric(12,2) not null default 0,

    status text not null default 'pending',

    payment_method text,
    payment_status text not null default 'unpaid',

    note text,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint orders_total_amount_non_negative
        check (total_amount >= 0),

    constraint orders_status_check
        check (
            status in (
                'pending',
                'confirmed',
                'packing',
                'shipped',
                'delivered',
                'cancelled'
            )
        ),

    constraint orders_payment_status_check
        check (
            payment_status in (
                'unpaid',
                'paid',
                'refunded'
            )
        )
);


-- ============================================================
-- 4. ORDER ITEMS
-- ============================================================

create table if not exists public.order_items (
    id bigint generated by default as identity primary key,

    order_id bigint not null
        references public.orders(id)
        on delete cascade,

    product_id bigint
        references public.products(id)
        on delete set null,

    product_name text not null,

    quantity integer not null default 1,

    unit_price numeric(12,2) not null default 0,

    subtotal numeric(12,2) not null default 0,

    created_at timestamptz not null default now(),

    constraint order_items_quantity_positive
        check (quantity > 0),

    constraint order_items_unit_price_non_negative
        check (unit_price >= 0),

    constraint order_items_subtotal_non_negative
        check (subtotal >= 0)
);


-- ============================================================
-- 5. STOCK MOVEMENTS
-- ============================================================

create table if not exists public.stock_movements (
    id bigint generated by default as identity primary key,

    product_id bigint not null
        references public.products(id)
        on delete cascade,

    movement_type text not null,

    quantity integer not null,

    stock_before integer not null default 0,
    stock_after integer not null default 0,

    note text,

    created_at timestamptz not null default now(),

    constraint stock_movement_type_check
        check (
            movement_type in (
                'stock_in',
                'stock_out',
                'adjustment',
                'sale',
                'return'
            )
        ),

    constraint stock_before_non_negative
        check (stock_before >= 0),

    constraint stock_after_non_negative
        check (stock_after >= 0)
);


-- ============================================================
-- 6. CUSTOMER NOTES
-- ============================================================

create table if not exists public.customer_notes (
    id bigint generated by default as identity primary key,

    customer_id bigint not null
        references public.customers(id)
        on delete cascade,

    note text not null,

    created_at timestamptz not null default now()
);


-- ============================================================
-- 7. INDEXES
-- ============================================================

create index if not exists products_active_idx
    on public.products(active);

create index if not exists products_created_at_idx
    on public.products(created_at desc);

create index if not exists customers_phone_idx
    on public.customers(phone);

create index if not exists customers_created_at_idx
    on public.customers(created_at desc);

create index if not exists orders_customer_id_idx
    on public.orders(customer_id);

create index if not exists orders_status_idx
    on public.orders(status);

create index if not exists orders_created_at_idx
    on public.orders(created_at desc);

create index if not exists order_items_order_id_idx
    on public.order_items(order_id);

create index if not exists stock_movements_product_id_idx
    on public.stock_movements(product_id);

create index if not exists stock_movements_created_at_idx
    on public.stock_movements(created_at desc);


-- ============================================================
-- 8. UPDATED_AT FUNCTION
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;


-- ============================================================
-- 9. UPDATED_AT TRIGGERS
-- ============================================================

drop trigger if exists products_set_updated_at
on public.products;

create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();


drop trigger if exists customers_set_updated_at
on public.customers;

create trigger customers_set_updated_at
before update on public.customers
for each row
execute function public.set_updated_at();


drop trigger if exists orders_set_updated_at
on public.orders;

create trigger orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();


-- ============================================================
-- 10. STOCK UPDATE FUNCTION
-- ============================================================

create or replace function public.change_product_stock(
    p_product_id bigint,
    p_quantity integer,
    p_movement_type text,
    p_note text default null
)
returns public.products
language plpgsql
security definer
set search_path = public
as $$
declare
    v_product public.products;
    v_new_stock integer;
begin

    select *
    into v_product
    from public.products
    where id = p_product_id
    for update;

    if not found then
        raise exception 'Product not found';
    end if;

    if p_movement_type in ('stock_in', 'return') then
        v_new_stock := v_product.stock + p_quantity;

    elsif p_movement_type in ('stock_out', 'sale') then
        v_new_stock := v_product.stock - p_quantity;

    elsif p_movement_type = 'adjustment' then
        v_new_stock := p_quantity;

    else
        raise exception 'Invalid stock movement type';
    end if;

    if v_new_stock < 0 then
        raise exception 'Not enough stock';
    end if;

    update public.products
    set
        stock = v_new_stock,
        updated_at = now()
    where id = p_product_id
    returning *
    into v_product;

    insert into public.stock_movements (
        product_id,
        movement_type,
        quantity,
        stock_before,
        stock_after,
        note
    )
    values (
        p_product_id,
        p_movement_type,
        p_quantity,
        case
            when p_movement_type = 'adjustment'
            then v_product.stock
            else
                case
                    when p_movement_type in ('stock_in', 'return')
                    then v_product.stock - p_quantity
                    else v_product.stock + p_quantity
                end
        end,
        v_new_stock,
        p_note
    );

    return v_product;
end;
$$;


-- ============================================================
-- 11. CUSTOMER SUMMARY FUNCTION
-- ============================================================

create or replace function public.refresh_customer_summary(
    p_customer_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin

    update public.customers c
    set
        total_orders = (
            select count(*)
            from public.orders o
            where o.customer_id = p_customer_id
              and o.status <> 'cancelled'
        ),

        total_spent = (
            select coalesce(sum(o.total_amount), 0)
            from public.orders o
            where o.customer_id = p_customer_id
              and o.status <> 'cancelled'
              and o.payment_status = 'paid'
        ),

        updated_at = now()

    where c.id = p_customer_id;

end;
$$;


-- ============================================================
-- 12. PRODUCT VIEW
-- ============================================================

create or replace view public.active_products
as
select
    id,
    name,
    description,
    price,
    color,
    sizes,
    image_url,
    stock,
    active,
    created_at,
    updated_at
from public.products
where active = true
order by created_at desc;


-- ============================================================
-- 13. CUSTOMER ORDER HISTORY VIEW
-- ============================================================

create or replace view public.customer_order_history
as
select
    o.id as order_id,
    o.customer_id,
    o.customer_name,
    o.customer_phone,
    o.customer_address,
    o.total_amount,
    o.status,
    o.payment_method,
    o.payment_status,
    o.note,
    o.created_at,

    count(oi.id) as item_count

from public.orders o

left join public.order_items oi
    on oi.order_id = o.id

group by
    o.id,
    o.customer_id,
    o.customer_name,
    o.customer_phone,
    o.customer_address,
    o.total_amount,
    o.status,
    o.payment_method,
    o.payment_status,
    o.note,
    o.created_at;


-- ============================================================
-- 14. ROW LEVEL SECURITY
-- ============================================================

alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.stock_movements enable row level security;
alter table public.customer_notes enable row level security;


-- ============================================================
-- 15. PRODUCTS POLICIES
-- ============================================================

drop policy if exists "Public can view active products"
on public.products;

create policy "Public can view active products"
on public.products
for select
using (active = true);


-- ============================================================
-- 16. CUSTOMER POLICIES
-- ============================================================

drop policy if exists "Public can create customers"
on public.customers;

create policy "Public can create customers"
on public.customers
for insert
with check (true);


-- ============================================================
-- 17. ORDER POLICIES
-- ============================================================

drop policy if exists "Public can create orders"
on public.orders;

create policy "Public can create orders"
on public.orders
for insert
with check (true);


drop policy if exists "Public can create order items"
on public.order_items;

create policy "Public can create order items"
on public.order_items
for insert
with check (true);


-- ============================================================
-- 18. CUSTOMER NOTES
-- ============================================================

drop policy if exists "Public can create customer notes"
on public.customer_notes;

create policy "Public can create customer notes"
on public.customer_notes
for insert
with check (true);


-- ============================================================
-- 19. ADMIN ACCESS
-- ============================================================
--
-- IMPORTANT:
-- Admin authentication should be added before allowing
-- public UPDATE/DELETE access.
--
-- Do NOT create unrestricted public UPDATE/DELETE policies.
--
-- The Admin Dashboard will later use authenticated admin
-- access to manage:
--
-- Products
-- Stock
-- Customers
-- Orders
-- Customer Notes
--
-- ============================================================


-- ============================================================
-- 20. STORAGE BUCKET
-- ============================================================
--
-- The existing Admin Panel already expects:
--
-- product-images
--
-- Create this bucket from Supabase Storage if it does not
-- already exist.
--
-- Product image uploads should be handled separately from
-- this SQL schema.
-- ============================================================


-- ============================================================
-- 21. SAMPLE PRODUCT DATA
-- ============================================================
--
-- Uncomment these only if you want test products.
--
-- insert into public.products
-- (
--     name,
--     description,
--     price,
--     color,
--     sizes,
--     image_url,
--     stock,
--     active
-- )
-- values
-- (
--     'Classic Polo',
--     'Premium classic men''s polo',
--     45000,
--     'Black',
--     'M, L, XL',
--     null,
--     10,
--     true
-- );


-- ============================================================
-- END OF SCHEMA
-- မဟာရန်ကုန် Classic Store
-- ============================================================
